### ISSUE TITLE
Adapter Absturz

### ISSUE THREAD

**Issue by RasputinBerry** [iobroker-community-adapters/ioBroker.frontier_silicon#46]
... wenn mein SILVERCREST sich aus dem WLAN verabschiedet (aus welchem Grund auch immer ...) meldet sich der Adapter mit div. Fehlern im Log und zeigt das gelbe Dreieck in der Instanz, siehe [https://forum.iobroker.net/topic/38177/neuer-adapter-undok-fsapi/81?_=1684915926481](url)

**Comment by mcm1957** [comment]
Fehler lt. Forum:

```
frontier_silicon.0 | 2023-05-23 19:51:48.206	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
frontier_silicon.0 | 2023-05-23 19:51:48.204	info	terminating
frontier_silicon.0 | 2023-05-23 19:51:48.191	error	Exception-Code: EHOSTUNREACH: connect EHOSTUNREACH 192.168.178.31:80
frontier_silicon.0 | 2023-05-23 19:51:48.189	error	Error: connect EHOSTUNREACH 192.168.178.31:80 at Function.AxiosError.from (/opt/iobroker/node_modules/iobroker.frontier_silicon/node_modules/axios/dist/node/axios.cjs:825:14) at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/iobroker.frontier_silicon/node_modules/axios/dist/node/axios.cjs:2973:25) at RedirectableRequest.emit (node:events:513:28) at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:14:24) at ClientRequest.emit (node:events:513:28) at Socket.socketErrorListener (node:_http_client:494:9) at Socket.emit (node:events:513:28) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21)
frontier_silicon.0 | 2023-05-23 19:51:48.184	error	unhandled promise rejection: connect EHOSTUNREACH 192.168.178.31:80
frontier_silicon.0 | 2023-05-23 19:51:48.181	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
frontier_silicon.0 | 2023-05-23 19:51:44.932	info	starting. Version 0.0.11 in /opt/iobroker/node_modules/iobroker.frontier_silicon, node: v16.20.0, js-controller: 4.0.24
frontier_silicon.0 | 2023-05-23 19:50:11.167	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
```

**Comment by RasputinBerry** [comment]
... SILVERCREST (wieder einmal) nicht mehr im WLAN und der Adpater meldet sich:
`<html><body>


frontier_silicon.0 | 2023-06-08 09:40:45.886 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
frontier_silicon.0 | 2023-06-08 09:40:45.884 | info | terminating
frontier_silicon.0 | 2023-06-08 09:40:45.871 | error | Exception-Code: EHOSTUNREACH: connect EHOSTUNREACH 192.168.178.31:80
frontier_silicon.0 | 2023-06-08 09:40:45.868 | error | Error:  connect EHOSTUNREACH 192.168.178.31:80    at Function.AxiosError.from  (/opt/iobroker/node_modules/iobroker.frontier_silicon/node_modules/axios/dist/node/axios.cjs:825:14)     at RedirectableRequest.handleRequestError  (/opt/iobroker/node_modules/iobroker.frontier_silicon/node_modules/axios/dist/node/axios.cjs:2973:25)     at RedirectableRequest.emit (node:events:513:28)    at  ClientRequest.eventHandlers.<computed>  (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)    at  ClientRequest.emit (node:events:513:28)    at Socket.socketErrorListener  (node:_http_client:494:9)    at Socket.emit (node:events:513:28)    at  emitErrorNT (node:internal/streams/destroy:157:8)    at emitErrorCloseNT  (node:internal/streams/destroy:122:3)    at processTicksAndRejections  (node:internal/process/task_queues:83:21)
frontier_silicon.0 | 2023-06-08 09:40:45.863 | error | unhandled promise rejection: connect EHOSTUNREACH 192.168.178.31:80
frontier_silicon.0 | 2023-06-08 09:40:45.861 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
frontier_silicon.0 | 2023-06-08 09:40:42.601 | info | starting. Version 0.0.11 in /opt/iobroker/node_modules/iobroker.frontier_silicon, node: v16.20.0, js-controller: 4.0.24
frontier_silicon.0 | 2023-06-08 09:40:09.085 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason


</body>
</html>`

**Comment by pdbjjens** [comment]
@RasputinBerry @mcm1957 
Danke für das weitere Protokoll. 
Die (UNCAUGHT_EXCEPTION) werde ich bei der nächsten Version des Adapters abfangen, so dass der Adapter nicht mehr abstürzt, sondern eine Error-Meldung ausgibt. Das wird aber vermutlich nicht verhindern, dass das Silvercrest Radio die WLAN-Verbindung verliert. Ich vermute hier nach wie vor Netzwerkprobleme.
Ich  melde mich hier, sobald hier auf GitHub eine Testversion vorliegt.

**Comment by RasputinBerry** [comment]
> Ich vermute hier nach wie vor Netzwerkprobleme.

Schon klar, dass das wohl nix mit dem Adapter zu tun hat. Das SILVERCREST Radio ist der einzige Netzteilnehmer, der immer mal wieder weg ist. Ich habe schon ein wenig recherchiert aber (noch) nix gefunden. 
Ansonsten ist bei mir kein Gerät auffällig. Ich lebe (erstmal) damit ...

**Comment by pdbjjens** [comment]
@RasputinBerry 
Hat das Radio eine feste Netzwerkadresse (bzw. immer dieselbe) zugewiesen bekommen?

**Comment by RasputinBerry** [comment]
... ja, via Fritz.Box festgelegt ... Du mußt Dir jetzt aber nicht dieses Problem zu deinem machen ...

**Comment by pdbjjens** [comment]
@RasputinBerry
Danke für Deine Mühe. 
Ich fürchte, Du hast die "alte" Version installiert (die "neue" logged u.a. nicht mehr die Meldung "Hallo PARSER"). 
Also um die "neue" v0.0.11 zu installieren ist es am besten, die "alte" komplett zu deinstallieren und dann den Adapter über URL zu installieren und zwar BENUTZERDEFINIERT und mit diesem Link [https://github.com/iobroker-community-adapters/ioBroker.frontier_silicon.git](https://github.com/iobroker-community-adapters/ioBroker.frontier_silicon.git)
Die Debug logs brauchst Du vorerst nicht einzuschalten, Falls der Fehler auftritt, wird das über info oder error Meldungen protokolliert. Sonst sieht man vor lauter debug Einträgen gar nichts mehr :-(

**Comment by RasputinBerry** [comment]
erl.
![grafik](https://github.com/iobroker-community-adapters/ioBroker.frontier_silicon/assets/56359831/34e836b3-6d81-48d5-9c30-147c29e2d156)

**Comment by pdbjjens** [comment]
@RasputinBerry 
Ich habe noch den Wiederaufbau der Session bei Verlust der Netzwerkverbindung hinzugefügt. Es wäre gut, wenn Du Deine Tests mit dem neusten GitHub-Stand des Adapters von heute Abend fortsetzen würdest.

**Comment by RasputinBerry** [comment]
@pdbjjens 
d.h. es gibt eine neuere Version (als o.g. 0.0.11 ?) und ich soll, wie von Dir beschrieben, nochmal frisch installieren ?

**Comment by pdbjjens** [comment]
@RasputinBerry 
Die Versionsnummer ist immer noch 0.0.11, weil ich kein neues Release gemacht habe, Ich habe lediglich den Code auf GitHub erweitert. Also bitte so verfahren, wie ich oben geschrieben habe.
![BenutzerDefiniert-Screenshot 2023-07-12 082331](https://github.com/iobroker-community-adapters/ioBroker.frontier_silicon/assets/60287544/0894e887-feaf-41b4-9755-9b9f66e5b0e8)

**Comment by pdbjjens** [comment]
@RasputinBerry 
Ich habe noch ein paar Verbesserungen am logging des Session(wieder)aufbaus vorgenommen. 

`2023-07-13 17:59:26.104 - info: frontier_silicon.0 (4728) starting. Version 0.0.11 (non-npm: iobroker-community-adapters/ioBroker.frontier_silicon#6cfe2d25c2820c1530d85bfae40b23c2bbae0da4) in C:/ioBroker/node_modules/iobroker.frontier_silicon, node: v18.16.0, js-controller: 4.0.24
2023-07-13 17:59:26.642 - info: frontier_silicon.0 (4728) Create Session
2023-07-13 17:59:26.658 - info: frontier_silicon.0 (4728) Session 659135579 with Device HAMA DIT2100MSBT @ 192.168.1.163 created
2023-07-13 18:01:57.753 - error: frontier_silicon.0 (4728) Session error, trying to reestablish session...
2023-07-13 18:01:58.775 - info: frontier_silicon.0 (4728) Create Session
2023-07-13 18:02:19.825 - error: frontier_silicon.0 (4728) Error: connect ETIMEDOUT 192.168.1.163:80
2023-07-13 18:02:19.825 - info: frontier_silicon.0 (4728) No session created, retry 9 more times
2023-07-13 18:02:19.825 - info: frontier_silicon.0 (4728) No connection, retrying...
2023-07-13 18:02:20.837 - info: frontier_silicon.0 (4728) Create Session
2023-07-13 18:02:41.871 - error: frontier_silicon.0 (4728) Error: connect ETIMEDOUT 192.168.1.163:80
2023-07-13 18:02:41.871 - info: frontier_silicon.0 (4728) No session created, retry 8 more times
2023-07-13 18:02:41.871 - info: frontier_silicon.0 (4728) No connection, retrying...
2023-07-13 18:02:42.877 - info: frontier_silicon.0 (4728) Create Session
2023-07-13 18:03:03.903 - error: frontier_silicon.0 (4728) Error: connect ETIMEDOUT 192.168.1.163:80
2023-07-13 18:03:03.903 - info: frontier_silicon.0 (4728) No session created, retry 7 more times
2023-07-13 18:03:03.903 - info: frontier_silicon.0 (4728) No connection, retrying...
2023-07-13 18:03:04.919 - info: frontier_silicon.0 (4728) Create Session
2023-07-13 18:03:25.957 - error: frontier_silicon.0 (4728) Error: connect ETIMEDOUT 192.168.1.163:80
2023-07-13 18:03:25.957 - info: frontier_silicon.0 (4728) No session created, retry 6 more times
2023-07-13 18:03:25.957 - info: frontier_silicon.0 (4728) No connection, retrying...
2023-07-13 18:03:26.972 - info: frontier_silicon.0 (4728) Create Session
2023-07-13 18:03:42.021 - info: frontier_silicon.0 (4728) Session 516657703 with Device HAMA DIT2100MSBT @ 192.168.1.163 created
`
Wenn es Dir hilft, Deine Radio-Verbindung zu überwachen, solltest Du die letzte GitHub Version von heute 17:45 installieren.

**Comment by RasputinBerry** [comment]
OK, erl., letze Variante installiert ...
_(Ich unterstelle, mit o.g. URL bekomme ich immer die neueste Variante)_

**Comment by pdbjjens** [comment]
@RasputinBerry 
Ja, sollte so sein... Zur Sicherheit kannst Du ja mal die ersten Zeilen des Adapter Starts mit meinem Protokoll, oben vergleichen. 
Wenn da sowas steht wie: "Session 659135579 with Device HAMA DIT2100MSBT @ 192.168.1.163 created"
dann hast Du die neuste Version installiert.
Noch zur Ergänzung: Nach 10 erfolglosen Session-Aufbauversuchen (ungefähr 4 Minuten) beendet sich der Adapter selbst (damit die Protokolldatei nicht vollgemüllt wird) und muss dann von Hand wieder neu gestartet werden. Wenn innerhalb der 4 Minuten die Verbindung zustande kommt, wird die Session wieder aufgebaut und der Adapter läuft weiter. Aber im Protokoll kannst Du das Ereignis natürlich sehen.
Wenn Dir sonst noch irgendwas auffällt (z.B. bestimmte Funktionen oder Stati sind plötzlich fehlerhaft oder anders als vorher, bitte melden. Ich möchte möglichst bald eine neue Version (voraussichtlich v0.1.0, da einige inkompatible Änderungen - siehe Readme) freigeben und da ist mir Dein Feedback sehr wichtig.

**Comment by RasputinBerry** [comment]
... dann war alles richtig ...
![grafik](https://github.com/iobroker-community-adapters/ioBroker.frontier_silicon/assets/56359831/5bfa865b-1e7b-4729-a3ec-f25dd892074c)
Ich beobachte ... und melde mich wenn etwas auffällig ist.
Als Tester bin ich (leider) nur bedingt geeignet. Ich nutze den Adapter produktiv nur zum Ein- und Ausschalten ... aber ich "spiele bei Gelegenheit mal etwas rum" ....

**Comment by Diginix** [comment]
Hatte heute auch folgende Adapterabstürze bis der Controller den Adapter hart gekillt hat:
```
2023-07-14 14:20:08.080 - error: frontier_silicon.0 (579028) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-07-14 14:20:08.082 - error: frontier_silicon.0 (579028) unhandled promise rejection: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 14:20:08.083 - error: frontier_silicon.0 (579028) Error: connect EHOSTUNREACH 192.168.2.51:80
    at Function.AxiosError.from (/opt/iobroker/node_modules/iobroker.frontier_silicon/node_modules/axios/dist/node/axios.cjs:825:14)
    at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/iobroker.frontier_silicon/node_modules/axios/dist/node/axios.cjs:2973:25)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-07-14 14:20:08.083 - error: frontier_silicon.0 (579028) Exception-Code: EHOSTUNREACH: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 14:20:08.088 - warn: frontier_silicon.0 (579028) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-07-14 14:20:08.701 - error: host.iobroker instance system.adapter.frontier_silicon.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-07-14 14:20:14.640 - error: frontier_silicon.0 (579075) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-07-14 14:20:14.642 - error: frontier_silicon.0 (579075) unhandled promise rejection: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 14:20:14.643 - error: frontier_silicon.0 (579075) Error: connect EHOSTUNREACH 192.168.2.51:80
    at Function.AxiosError.from (/opt/iobroker/node_modules/iobroker.frontier_silicon/node_modules/axios/dist/node/axios.cjs:825:14)
    at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/iobroker.frontier_silicon/node_modules/axios/dist/node/axios.cjs:2973:25)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-07-14 14:20:14.643 - error: frontier_silicon.0 (579075) Exception-Code: EHOSTUNREACH: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 14:20:14.648 - warn: frontier_silicon.0 (579075) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-07-14 14:20:15.260 - error: host.iobroker instance system.adapter.frontier_silicon.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-07-14 14:20:21.488 - error: frontier_silicon.0 (579115) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-07-14 14:20:21.489 - error: frontier_silicon.0 (579115) unhandled promise rejection: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 14:20:21.490 - error: frontier_silicon.0 (579115) Error: connect EHOSTUNREACH 192.168.2.51:80
    at Function.AxiosError.from (/opt/iobroker/node_modules/iobroker.frontier_silicon/node_modules/axios/dist/node/axios.cjs:825:14)
    at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/iobroker.frontier_silicon/node_modules/axios/dist/node/axios.cjs:2973:25)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-07-14 14:20:21.491 - error: frontier_silicon.0 (579115) Exception-Code: EHOSTUNREACH: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 14:20:21.495 - warn: frontier_silicon.0 (579115) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-07-14 14:20:22.206 - error: host.iobroker instance system.adapter.frontier_silicon.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-07-14 14:20:22.207 - warn: host.iobroker Do not restart adapter system.adapter.frontier_silicon.0 because restart loop detected
```
Loglevel des Adapter ist warn. Mehr kann ich leider nicht liefern.

Adapter: v0.0.11
nodejs: 16.20.1
js-controller: 5.0.7

**Comment by pdbjjens** [comment]
@Diginix 
Diese Probleme sollten mit der momentan auf **GitHub** befindlichen Version (noch 0.0.11) behoben sein. Wäre gut, wenn Du die Version so wie ich das oben beschrieben habe, installieren würdest. Damit sollten alle Probleme mit nicht erreichbaren Hosts abgefangen werden. Ich würde mich freuen, mit Dir einen weiteren "Alfa-Tester" zu haben.

**Comment by Diginix** [comment]
@pdbjjens 0.0.11 von GIT funktioniert wie von dir beschrieben ohne Crash bei nicht verfügbarem Gerät:
```
2023-07-14 19:09:24.188 - info: frontier_silicon.0 (614016) starting. Version 0.0.11 (non-npm: iobroker-community-adapters/ioBroker.frontier_silicon#6cfe2d25c2820c1530d85bfae40b23c2bbae0da4) in /opt/iobroker/node_modules/iobroker.frontier_silicon, node: v16.20.1, js-controller: 5.0.7
2023-07-14 19:09:24.476 - info: frontier_silicon.0 (614016) Create Session
2023-07-14 19:09:24.507 - info: frontier_silicon.0 (614016) Session 332004744 with Device Medion Radio MD 87090 @ 192.168.2.51 created
2023-07-14 19:13:13.489 - error: frontier_silicon.0 (614016) Session error, trying to reestablish session...
2023-07-14 19:13:23.988 - info: frontier_silicon.0 (614016) Create Session
2023-07-14 19:13:27.054 - error: frontier_silicon.0 (614016) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 19:13:27.055 - info: frontier_silicon.0 (614016) No session created, retry 9 more times
2023-07-14 19:13:27.058 - info: frontier_silicon.0 (614016) No connection, retrying...
2023-07-14 19:13:37.066 - info: frontier_silicon.0 (614016) Create Session
2023-07-14 19:13:40.142 - error: frontier_silicon.0 (614016) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 19:13:40.143 - info: frontier_silicon.0 (614016) No session created, retry 8 more times
2023-07-14 19:13:40.147 - info: frontier_silicon.0 (614016) No connection, retrying...
2023-07-14 19:13:50.149 - info: frontier_silicon.0 (614016) Create Session
2023-07-14 19:13:53.230 - error: frontier_silicon.0 (614016) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 19:13:53.231 - info: frontier_silicon.0 (614016) No session created, retry 7 more times
2023-07-14 19:13:53.255 - info: frontier_silicon.0 (614016) No connection, retrying...
2023-07-14 19:14:03.258 - info: frontier_silicon.0 (614016) Create Session
2023-07-14 19:14:05.295 - error: frontier_silicon.0 (614016) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 19:14:05.295 - info: frontier_silicon.0 (614016) No session created, retry 6 more times
2023-07-14 19:14:05.298 - info: frontier_silicon.0 (614016) No connection, retrying...
2023-07-14 19:14:15.377 - info: frontier_silicon.0 (614016) Create Session
2023-07-14 19:14:18.446 - error: frontier_silicon.0 (614016) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 19:14:18.447 - info: frontier_silicon.0 (614016) No session created, retry 5 more times
2023-07-14 19:14:18.459 - info: frontier_silicon.0 (614016) No connection, retrying...
2023-07-14 19:14:28.535 - info: frontier_silicon.0 (614016) Create Session
2023-07-14 19:14:31.726 - error: frontier_silicon.0 (614016) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 19:14:31.727 - info: frontier_silicon.0 (614016) No session created, retry 4 more times
2023-07-14 19:14:31.732 - info: frontier_silicon.0 (614016) No connection, retrying...
2023-07-14 19:14:41.734 - info: frontier_silicon.0 (614016) Create Session
2023-07-14 19:14:44.814 - error: frontier_silicon.0 (614016) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 19:14:44.815 - info: frontier_silicon.0 (614016) No session created, retry 3 more times
2023-07-14 19:14:45.246 - info: frontier_silicon.0 (614016) No connection, retrying...
2023-07-14 19:14:55.248 - info: frontier_silicon.0 (614016) Create Session
2023-07-14 19:14:56.143 - error: frontier_silicon.0 (614016) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 19:14:56.143 - info: frontier_silicon.0 (614016) No session created, retry 2 more times
2023-07-14 19:14:56.146 - info: frontier_silicon.0 (614016) No connection, retrying...
2023-07-14 19:15:06.221 - info: frontier_silicon.0 (614016) Create Session
2023-07-14 19:15:09.294 - error: frontier_silicon.0 (614016) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-14 19:15:09.294 - info: frontier_silicon.0 (614016) No session created, retry 1 more times
2023-07-14 19:15:09.342 - info: frontier_silicon.0 (614016) No connection, retrying...
2023-07-14 19:15:20.382 - info: frontier_silicon.0 (614016) Create Session
2023-07-14 19:15:23.636 - info: frontier_silicon.0 (614016) Terminated (ADAPTER_REQUESTED_TERMINATION): Adapter terminated after 10 Session Re-establish Attempts
2023-07-14 19:15:23.845 - info: frontier_silicon.0 (614016) No connection, retrying...
2023-07-14 19:23:04.767 - info: frontier_silicon.0 (615995) starting. Version 0.0.11 (non-npm: iobroker-community-adapters/ioBroker.frontier_silicon#6cfe2d25c2820c1530d85bfae40b23c2bbae0da4) in /opt/iobroker/node_modules/iobroker.frontier_silicon, node: v16.20.1, js-controller: 5.0.7
2023-07-14 19:23:04.997 - info: frontier_silicon.0 (615995) Create Session
2023-07-14 19:23:05.029 - info: frontier_silicon.0 (615995) Session 1859522517 with Device Medion Radio MD 87090 @ 192.168.2.51 created

```

**Comment by pdbjjens** [comment]
@Diginix 
Danke für den Schnelltest. Wenn Du magst, könntest Du auch noch den Fall testen, dass die Verbindung zurückkehrt, bevor die 10 Verbindungsversuche durch sind.
Es wäre schön, wenn Du die GitHub-Version in Deiner Umgebung noch eine Weile laufen lassen und mir mitteilen würdest ob irgendwelche Probleme auftauchen, die mit der bisherigen Version nicht da waren.

**Comment by Diginix** [comment]
Stimmt, das kann ich morgen auch noch testen. Und generelle Funktionstest ebenso. Vorhin hab ich nur An/Aus & Senderwechsel getestet. Vermute aber dass sich an der Steuerung ja nichts verändert haben sollte durch deine Optimierung.

**Comment by Diginix** [comment]
Reconnect noch während der 10 Versuche funktioniert auch:
```
2023-07-15 09:50:13.997 - info: frontier_silicon.0 (724701) starting. Version 0.0.11 (non-npm: iobroker-community-adapters/ioBroker.frontier_silicon#6cfe2d25c2820c1530d85bfae40b23c2bbae0da4) in /opt/iobroker/node_modules/iobroker.frontier_silicon, node: v16.20.1, js-controller: 5.0.7
2023-07-15 09:50:14.181 - info: frontier_silicon.0 (724701) Create Session
2023-07-15 09:50:14.204 - info: frontier_silicon.0 (724701) Session 1976679695 with Device Medion Radio MD 87090 @ 192.168.2.51 created
2023-07-15 09:58:18.384 - error: frontier_silicon.0 (724701) Session error, trying to reestablish session...
2023-07-15 09:58:28.394 - info: frontier_silicon.0 (724701) Create Session
2023-07-15 09:58:31.214 - error: frontier_silicon.0 (724701) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-15 09:58:31.215 - info: frontier_silicon.0 (724701) No session created, retry 9 more times
2023-07-15 09:58:31.219 - info: frontier_silicon.0 (724701) No connection, retrying...
2023-07-15 09:58:41.294 - info: frontier_silicon.0 (724701) Create Session
2023-07-15 09:58:44.366 - error: frontier_silicon.0 (724701) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-15 09:58:44.367 - info: frontier_silicon.0 (724701) No session created, retry 8 more times
2023-07-15 09:58:44.370 - info: frontier_silicon.0 (724701) No connection, retrying...
2023-07-15 09:58:54.395 - info: frontier_silicon.0 (724701) Create Session
2023-07-15 09:58:57.454 - error: frontier_silicon.0 (724701) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-15 09:58:57.455 - info: frontier_silicon.0 (724701) No session created, retry 7 more times
2023-07-15 09:58:57.458 - info: frontier_silicon.0 (724701) No connection, retrying...
2023-07-15 09:59:07.481 - info: frontier_silicon.0 (724701) Create Session
2023-07-15 09:59:10.574 - error: frontier_silicon.0 (724701) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-15 09:59:10.575 - info: frontier_silicon.0 (724701) No session created, retry 6 more times
2023-07-15 09:59:10.578 - info: frontier_silicon.0 (724701) No connection, retrying...
2023-07-15 09:59:20.581 - info: frontier_silicon.0 (724701) Create Session
2023-07-15 09:59:23.662 - error: frontier_silicon.0 (724701) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-15 09:59:23.662 - info: frontier_silicon.0 (724701) No session created, retry 5 more times
2023-07-15 09:59:23.665 - info: frontier_silicon.0 (724701) No connection, retrying...
2023-07-15 09:59:33.667 - info: frontier_silicon.0 (724701) Create Session
2023-07-15 09:59:36.751 - error: frontier_silicon.0 (724701) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-15 09:59:36.751 - info: frontier_silicon.0 (724701) No session created, retry 4 more times
2023-07-15 09:59:36.756 - info: frontier_silicon.0 (724701) No connection, retrying...
2023-07-15 09:59:46.758 - info: frontier_silicon.0 (724701) Create Session
2023-07-15 09:59:49.838 - error: frontier_silicon.0 (724701) Error: connect EHOSTUNREACH 192.168.2.51:80
2023-07-15 09:59:49.839 - info: frontier_silicon.0 (724701) No session created, retry 3 more times
2023-07-15 09:59:49.841 - info: frontier_silicon.0 (724701) No connection, retrying...
2023-07-15 09:59:59.844 - info: frontier_silicon.0 (724701) Create Session
2023-07-15 10:00:00.007 - info: frontier_silicon.0 (724701) Session 511517791 with Device Medion Radio MD 87090 @ 192.168.2.51 created

```

**Comment by pdbjjens** [comment]
@Diginix 
Danke für Dein Feedback. Demnächst werde ich dann eine neue Version herausgeben, voraussichtlich als major release v1.0.0 weil ein paar "Breaking Changes" z.B.: node>=14, js-contoller>=4, admin>=5, Json Config drin sind.
Bis dahin wäre es gut, wenn Du weiterhin beobachten würdest, ob irgendwelche Probleme auffallen.

**Comment by Harry-58** [comment]
Noch ein Hinweis.
Die Version 0.1.0 stürzte nach dem Update mit folgender Meldung ab:
AxiosError: Request failed with status code 403
Nachdem ich die Geheimzahl neu eingegeben habe, lief der Adapter.
Die Geheimzahl war aber die gleiche, wie vor dem Update!

**Comment by pdbjjens** [comment]
@RasputinBerry @Diginix @Harry-58 
This issue is fixed with release v0.1.1 #83
